export const services = [
  {
    id: 'desarrollo-medida',
    title: 'Desarrollo a Medida',
    subtitle: 'Software que se adapta a tu negocio',
    description: 'Creamos soluciones de software personalizadas que se integran perfectamente con los procesos existentes de tu empresa. Desde aplicaciones web hasta sistemas empresariales complejos.',
    features: [
      'Análisis profundo de requerimientos',
      'Arquitectura escalable y moderna',
      'Pruebas automatizadas',
      'Documentación técnica completa',
      'Soporte post-lanzamiento',
    ],
    icon: 'code',
  },
  {
    id: 'soporte-tecnico',
    title: 'Soporte Técnico',
    subtitle: 'Resolución rápida de incidencias',
    description: 'Nuestro equipo de expertos está disponible para resolver cualquier incidencia técnica. Tiempos de respuesta garantizados según tu nivel de servicio.',
    features: [
      'Soporte por múltiples canales',
      'SLA de respuesta garantizado',
      'Escalamiento automático',
      'Base de conocimiento dedicada',
      'Reportes de incidencias',
    ],
    icon: 'support',
  },
  {
    id: 'monitoreo',
    title: 'Monitoreo 24/7',
    subtitle: 'Vigilancia continua de tus sistemas',
    description: 'Supervisamos la salud y rendimiento de tu infraestructura las 24 horas del día. Detectamos y resolvemos problemas antes de que impacten a tus usuarios.',
    features: [
      'Monitoreo en tiempo real',
      'Alertas proactivas',
      'Dashboards de rendimiento',
      'Análisis de tendencias',
      'Informes mensuales detallados',
    ],
    icon: 'monitor',
  },
  {
    id: 'backups',
    title: 'Backups y Seguridad',
    subtitle: 'Protección integral de datos',
    description: 'Implementamos estrategias de respaldo automatizado y seguridad para garantizar la integridad y disponibilidad de tu información crítica.',
    features: [
      'Respaldos automáticos programados',
      'Retención configurable',
      'Encriptación en reposo y tránsito',
      'Pruebas de restauración periódicas',
      'Cumplimiento normativo',
    ],
    icon: 'shield',
  },
  {
    id: 'consultoria',
    title: 'Consultoría IT',
    subtitle: 'Estrategia tecnológica a tu medida',
    description: 'Asesoramos a tu equipo en la toma de decisiones tecnológicas. Desde la selección de plataformas hasta la optimización de procesos existentes.',
    features: [
      'Auditoría tecnológica',
      'Hoja de ruta estratégica',
      'Optimización de costos',
      'Modernización de sistemas',
      'Capacitación de equipos',
    ],
    icon: 'consulting',
  },
  {
    id: 'migraciones',
    title: 'Migraciones',
    subtitle: 'Transición segura a nuevas plataformas',
    description: 'Gestionamos migraciones complejas de infraestructura, bases de datos y aplicaciones con cero pérdida de datos y mínima interrupción del servicio.',
    features: [
      'Planificación detallada',
      'Migración gradual o big-bang',
      'Validación de integridad',
      'Rollback garantizado',
      'Soporte post-migración',
    ],
    icon: 'migrate',
  },
];
